<template>
  <q-breadcrumbs
    v-if="items.length > 0"
    :separator="separator"
    :active-color="activeColor"
    :separator-color="separatorColor"
    class="breadcrumbs"
  >
    <q-breadcrumbs-el
      v-for="(item, index) in items"
      :key="index"
      :label="item.label"
      :icon="item.icon"
      :to="item.to"
      :clickable="!!item.to && index !== items.length - 1"
    />
  </q-breadcrumbs>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vue-router';

export interface BreadcrumbItem {
  label: string;
  icon?: string;
  to?: string | { name: string; params?: any };
}

interface Props {
  items?: BreadcrumbItem[];
  separator?: string;
  activeColor?: string;
  separatorColor?: string;
  autoGenerate?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  separator: '/',
  activeColor: 'primary',
  separatorColor: 'grey-7',
  autoGenerate: true
});

const route = useRoute();

// Auto-generate breadcrumbs from route
const autoGeneratedItems = computed<BreadcrumbItem[]>(() => {
  if (!props.autoGenerate || props.items) {
    return props.items || [];
  }

  const items: BreadcrumbItem[] = [];
  const pathSegments = route.path.split('/').filter(Boolean);

  // Add home
  items.push({
    label: 'Home',
    icon: 'home',
    to: '/'
  });

  // Build breadcrumbs from path
  let currentPath = '';
  pathSegments.forEach((segment, index) => {
    currentPath += `/${segment}`;

    // Skip UUID segments
    if (isUUID(segment)) {
      return;
    }

    // Format label
    const label = segment
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');

    items.push({
      label,
      to: index === pathSegments.length - 1 ? undefined : currentPath
    });
  });

  return items;
});

const items = computed(() => {
  return props.items || autoGeneratedItems.value;
});

function isUUID(str: string): boolean {
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  return uuidRegex.test(str);
}
</script>

<style scoped lang="scss">
.breadcrumbs {
  font-size: 14px;

  :deep(.q-breadcrumbs__el) {
    &:hover {
      text-decoration: underline;
    }
  }
}
</style>
