<template>
  <q-page class="legal-page">
    <section class="legal-hero">
      <h1>Terms of Service</h1>
      <p>Last updated: January 6, 2025</p>
    </section>

    <section class="legal-content">
      <div class="legal-container">
        <article class="legal-article">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using SynthStack ("Service") at synthstack.app, you agree to be bound 
            by these Terms of Service ("Terms"). If you disagree with any part of these terms, 
            you may not access the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            SynthStack is an AI-native SaaS platform that provides AI copilot assistance, project 
            management tools, and business automation features. The Service includes:
          </p>
          <ul>
            <li>AI Copilot with specialized agents (Researcher, Marketer, Developer, SEO Writer, Designer, Assistant)</li>
            <li>Project and task management</li>
            <li>Client portal and invoicing</li>
            <li>Content creation and management via Directus CMS</li>
            <li>Cross-platform applications (web, iOS, Android, desktop)</li>
            <li>API access for integrations</li>
          </ul>

          <h2>3. User Accounts</h2>
          <h3>3.1 Account Creation</h3>
          <p>
            Some features are available without an account. Creating an account requires a valid 
            email address and grants access to AI copilot features, project management, and sync capabilities.
          </p>
          <h3>3.2 Account Security</h3>
          <p>
            You are responsible for maintaining the security of your account credentials. 
            We recommend enabling multi-factor authentication for enhanced security.
            Notify us immediately of any unauthorized access at <a href="mailto:team@manic.agency">team@manic.agency</a>.
          </p>
          <h3>3.3 Account Termination</h3>
          <p>
            We reserve the right to suspend or terminate accounts that violate these Terms 
            or engage in abusive behavior. You may close your account at any time through account settings.
          </p>

          <h2>4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any illegal purpose or to promote illegal activities</li>
            <li>Upload malicious files or attempt to compromise our systems</li>
            <li>Scrape, harvest, or collect data without permission</li>
            <li>Circumvent usage limits, quotas, or access restrictions</li>
            <li>Impersonate others or misrepresent your identity</li>
            <li>Share content that infringes intellectual property rights</li>
            <li>Use automated tools to access the Service without prior approval</li>
            <li>Use AI features to generate harmful, illegal, or misleading content</li>
            <li>Attempt to reverse-engineer, decompile, or extract AI model weights</li>
            <li>Use the Service to build a competing product</li>
            <li>Resell or redistribute the Service without authorization</li>
          </ul>

          <h2>5. AI Usage & Limitations</h2>
          <h3>5.1 AI-Generated Content</h3>
          <p>
            Content generated by our AI copilot features is provided as-is. You are responsible 
            for reviewing, editing, and validating AI-generated content before use. AI outputs 
            may contain errors, biases, or inaccuracies.
          </p>
          <h3>5.2 No Professional Advice</h3>
          <p>
            AI-generated content does not constitute professional advice (legal, medical, financial, 
            or otherwise). Consult qualified professionals for professional decisions.
          </p>
          <h3>5.3 Usage Limits</h3>
          <p>
            AI features are subject to usage limits based on your subscription tier. Exceeding 
            limits may result in temporary restrictions until your quota resets.
          </p>

          <h2>6. Intellectual Property</h2>
          <h3>6.1 Our Content</h3>
          <p>
            The Service, including its design, code, algorithms, and content (excluding user content), 
            is owned by SynthStack and protected by copyright, trademark, and other laws.
          </p>
          <h3>6.2 Your Content</h3>
          <p>
            You retain ownership of content you create and upload. By using the Service, you grant us 
            a limited license to process, store, and display your content for the purpose of providing 
            the Service. We do not claim ownership of your content.
          </p>
          <h3>6.3 AI-Generated Content</h3>
          <p>
            Subject to applicable law and your compliance with these Terms, you own the rights to 
            AI-generated content created through your use of the Service. You are responsible for 
            ensuring such use complies with applicable laws.
          </p>
          <h3>6.4 Feedback</h3>
          <p>
            If you provide feedback, suggestions, or ideas, you grant us a non-exclusive, perpetual, 
            royalty-free license to use such feedback for any purpose.
          </p>

          <h2>7. Subscription and Payments</h2>
          <h3>7.1 Free Tier</h3>
          <p>
            Basic features are available free of charge with usage limits as described on our pricing page.
          </p>
          <h3>7.2 Paid Subscriptions</h3>
          <p>
            Premium features require a paid subscription. Subscriptions are billed monthly or annually 
            and automatically renew unless cancelled. Prices are subject to change with 30 days notice.
          </p>
          <h3>7.3 Billing</h3>
          <p>
            Payments are processed securely through Stripe. You authorize us to charge your payment 
            method on a recurring basis. Failed payments may result in service suspension.
          </p>
          <h3>7.4 Refunds</h3>
          <p>
            We offer a 14-day money-back guarantee for new subscriptions. Contact 
            <a href="mailto:team@manic.agency">team@manic.agency</a> for refund requests.
            Refunds are not available for partial subscription periods after 14 days.
          </p>
          <h3>7.5 Cancellation</h3>
          <p>
            You may cancel your subscription at any time through account settings. Access continues 
            until the end of your current billing period.
          </p>

          <h2>8. Data & Privacy</h2>
          <p>
            Your use of the Service is subject to our <router-link to="/privacy">
              Privacy Policy
            </router-link>, 
            which describes how we collect, use, and protect your data. You consent to the 
            collection and use of data as described in the Privacy Policy.
          </p>

          <h2>9. Third-Party Services</h2>
          <p>
            The Service may integrate with third-party services (Stripe, OpenAI, etc.). Your use 
            of such services is subject to their respective terms and privacy policies. We are 
            not responsible for third-party services.
          </p>

          <h2>10. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, 
            EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, 
            ERROR-FREE, OR SECURE. AI-GENERATED CONTENT MAY CONTAIN ERRORS OR INACCURACIES.
          </p>

          <h2>11. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, 
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO 
            LOSS OF PROFITS, DATA, USE, OR GOODWILL.
          </p>
          <p>
            Our total liability shall not exceed the amount you paid us in the 12 months 
            preceding the claim, or $100, whichever is greater.
          </p>

          <h2>12. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless SynthStack and its affiliates from any claims, 
            damages, or expenses arising from your use of the Service, your content, or your 
            violation of these Terms.
          </p>

          <h2>13. Service Modifications</h2>
          <p>
            We reserve the right to modify, suspend, or discontinue any part of the Service 
            at any time. We will provide reasonable notice for significant changes that affect 
            your use of the Service.
          </p>

          <h2>14. Changes to Terms</h2>
          <p>
            We may modify these Terms at any time. We will provide notice of significant changes 
            via email or on the Service. Continued use after changes constitutes acceptance.
            If you disagree with changes, you must stop using the Service.
          </p>

          <h2>15. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the State of Delaware, United States, 
            without regard to conflict of law provisions.
          </p>

          <h2>16. Dispute Resolution</h2>
          <p>
            Any disputes shall be resolved through binding arbitration administered by JAMS 
            under its Streamlined Arbitration Rules, except for claims seeking injunctive relief. 
            You waive the right to participate in class actions or class-wide arbitration.
          </p>

          <h2>17. Severability</h2>
          <p>
            If any provision of these Terms is found unenforceable, the remaining provisions 
            will continue in effect.
          </p>

          <h2>18. Entire Agreement</h2>
          <p>
            These Terms, together with our Privacy Policy and any other policies referenced herein, 
            constitute the entire agreement between you and SynthStack regarding the Service.
          </p>

          <h2>19. Contact</h2>
          <p>
            For questions about these Terms, contact us at:<br>
            Email: <a href="mailto:team@manic.agency">team@manic.agency</a><br>
            General: <a href="mailto:team@manic.agency">team@manic.agency</a>
          </p>
        </article>
      </div>
    </section>
  </q-page>
</template>

<script setup lang="ts">
</script>

<style lang="scss" scoped>
@import './legal-styles.scss';
</style>
